repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: 'v0.9.3'
  hooks:
    - id: ruff
      args: [--fix]
      name: 'backend: ruff (check and fix)'
      pass_filenames: false
      always_run: true
      files: ^backend/
    - id: ruff
      args: [--select=I, --fix]
      name: 'backend: ruff (import sorting)'
      pass_filenames: false
      always_run: true
      files: ^backend/
    - id: ruff-format
      name: 'backend: ruff (format)'
      pass_filenames: false
      always_run: true
      files: ^backend/

- repo: local
  hooks:
    - id: commit-msg-template
      name: Check commit message format
      entry: python .pre-commit_msg_template.py
      language: python
      stages: [commit-msg]
      always_run: true

    - id: frontend-lint
      name: 'frontend: eslint'
      entry: bash -c 'cd frontend && pnpm run lint && pnpm run format'
      language: system
      files: ^frontend/
      pass_filenames: false
      always_run: true
