repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
    - id: end-of-file-fixer
      name: 'global: fix end of files'
    - id: trailing-whitespace
      name: 'global: trim trailing whitespace'
    - id: check-added-large-files
      name: 'global: check for large files'
    - id: check-merge-conflict
      name: 'global: check for merge conflicts'
    - id: check-case-conflict
      name: 'global: check for case conflicts'

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: 'v0.11.0'
  hooks:
    - id: ruff
      args: [--fix]
      name: 'backend: ruff (check and fix)'
      pass_filenames: false
      always_run: true
      files: ^backend/
    - id: ruff
      args: [--select=I, --fix]
      name: 'backend: ruff (import sorting)'
      pass_filenames: false
      always_run: true
      files: ^backend/
    - id: ruff-format
      name: 'backend: ruff (format)'
      pass_filenames: false
      always_run: true
      files: ^backend/

- repo: local
  hooks:
    - id: commit-msg-template
      name: 'global: check commit message format'
      entry: python .pre-commit_msg_template.py
      language: python
      stages: [commit-msg]
      always_run: true

    - id: frontend-lint
      name: 'frontend: eslint'
      entry: bash -c 'cd frontend && pnpm run lint && pnpm run format'
      language: system
      files: ^frontend/
      pass_filenames: false
      always_run: true
